### ISSUE TITLE
Clarification for documentation on delay

### ISSUE THREAD

**Issue by p810** [arei/functionary#2]
> delay runs n milliseconds into the future where it then scheduled the function for execution at the next idle time.

Is my understanding correct that `delay()` will run at the next idle time *after* the amount of time specified (*n* milliseconds)?

**Comment by arei** [comment]
Yes, after the delay has elapsed the function will be placed on the event stack to be executed at the next possible opportunity. It is essentially the same as a setTimeout call.

**Comment by p810** [comment]
Thanks!
